name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: thaibigdata
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./deployment/Dockerfile
        push: true
        tags: |
          thaibigdata/dataops-pipeline:latest
          thaibigdata/dataops-pipeline:${{ github.sha }}
        cache-from: type=registry,ref=thaibigdata/dataops-pipeline:buildcache
        cache-to: type=registry,ref=thaibigdata/dataops-pipeline:buildcache,mode=max
    
    - name: Notify success
      run: |
        echo "✅ Docker image pushed successfully!"
        echo "Image tags:"
        echo "  - thaibigdata/dataops-pipeline:latest"
        echo "  - thaibigdata/dataops-pipeline:${{ github.sha }}"
        echo ""
        echo "Jenkins will handle the deployment on the production server."
